// Copyright © 2026. Citrix Systems, Inc.

package testresource

import (
	"context"
	"net/http"
)

// Test Resource type for organizing test cases
type ExecuteWithRetryTestResource struct{}

var _ = &ExecuteWithRetryTestResource{}

// Mock client and wrapper types
type MockClient struct{}

type MockRequestWrapper struct{}

func (m MockRequestWrapper) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

func (m MockRequestWrapper) Async(async bool) MockRequestWrapper {
	return m
}

// Mock citrixdaasclient and citrixclient package functions
var citrixdaasclient = mockCitrixClient{}
var citrixclient = mockCitrixClient{}

type mockCitrixClient struct{}

func (m mockCitrixClient) ExecuteWithRetry(request any, client *MockClient) (any, *http.Response, error) {
	return nil, nil, nil
}

func (m mockCitrixClient) AddRequestData(request any, client *MockClient) MockRequestWrapper {
	return MockRequestWrapper{}
}

// Mock request types following autogenerated naming convention: Api<Method><Function>Request
type ApiGetHypervisorRequest struct{}

func (r ApiGetHypervisorRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

type ApiFetchAdministratorsRequest struct{}

func (r ApiFetchAdministratorsRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

type ApiCreateHypervisorRequest struct{}

func (r ApiCreateHypervisorRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

type ApiUpdateHypervisorRequest struct{}

func (r ApiUpdateHypervisorRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

type ApiDeleteHypervisorRequest struct{}

func (r ApiDeleteHypervisorRequest) Execute() (*http.Response, error) {
	return nil, nil
}

// Mock request types with service name in between: Api<Service><Method><Function>Request
// This pattern appears in real code like ApiTagsGetTagRequest, ApiDeliveryGroupsGetDeliveryGroupRequest
type ApiTagsGetTagRequest struct{}

func (r ApiTagsGetTagRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

type ApiDeliveryGroupsGetDeliveryGroupRequest struct{}

func (r ApiDeliveryGroupsGetDeliveryGroupRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

type ApiHypervisorsGetHypervisorsAndResourcePoolsRequest struct{}

func (r ApiHypervisorsGetHypervisorsAndResourcePoolsRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

type ApiMachineCatalogsListMachineCatalogsRequest struct{}

func (r ApiMachineCatalogsListMachineCatalogsRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

// StoreFront mock request types following convention: STF<Service><Method><Function>Request
type STFDeploymentGetSTFDeploymentRequest struct{}

func (r STFDeploymentGetSTFDeploymentRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

type STFDeploymentCreateSTFDeploymentRequest struct{}

func (r STFDeploymentCreateSTFDeploymentRequest) Execute() (any, *http.Response, error) {
	return nil, nil, nil
}

type STFDeploymentSetSTFDeploymentRequest struct{}

func (r STFDeploymentSetSTFDeploymentRequest) Execute() (*http.Response, error) {
	return nil, nil
}

type STFDeploymentClearSTFDeploymentRequest struct{}

func (r STFDeploymentClearSTFDeploymentRequest) Execute() (*http.Response, error) {
	return nil, nil
}

// Valid: Using ExecuteWithRetry for GET operations
func (r *ExecuteWithRetryTestResource) ValidGetWithRetry(ctx context.Context, client *MockClient) {
	getRequest := ApiGetHypervisorRequest{}
	_, _, _ = citrixdaasclient.ExecuteWithRetry(getRequest, client)
}

// Valid: Using AddRequestData().Execute() for non-GET operations (Create, Update, Delete)
func (r *ExecuteWithRetryTestResource) ValidCreateWithAddRequestData(ctx context.Context, client *MockClient) {
	createRequest := ApiCreateHypervisorRequest{}
	_, _, _ = citrixdaasclient.AddRequestData(createRequest, client).Execute()
}

func (r *ExecuteWithRetryTestResource) ValidUpdateWithAddRequestData(ctx context.Context, client *MockClient) {
	updateRequest := ApiUpdateHypervisorRequest{}
	_, _, _ = citrixdaasclient.AddRequestData(updateRequest, client).Execute()
}

func (r *ExecuteWithRetryTestResource) ValidDeleteWithAddRequestData(ctx context.Context, client *MockClient) {
	deleteRequest := ApiDeleteHypervisorRequest{}
	_, _, _ = citrixdaasclient.AddRequestData(deleteRequest, client).Execute()
}

// Valid: Using AddRequestData().Async().Execute() for non-GET operations
func (r *ExecuteWithRetryTestResource) ValidAsyncWithAddRequestData(ctx context.Context, client *MockClient) {
	updateRequest := ApiUpdateHypervisorRequest{}
	_, _, _ = citrixdaasclient.AddRequestData(updateRequest, client).Async(true).Execute()
}

// Valid: Using citrixclient alias (used in test files)
func (r *ExecuteWithRetryTestResource) ValidWithCitrixclientAlias(ctx context.Context, client *MockClient) {
	deleteRequest := ApiDeleteHypervisorRequest{}
	_, _, _ = citrixclient.AddRequestData(deleteRequest, client).Execute()
}

// violations:1
// Invalid: Direct Execute() call without wrapper
func (r *ExecuteWithRetryTestResource) InvalidDirectExecute(ctx context.Context) {
	request := ApiGetHypervisorRequest{}
	_, _, _ = request.Execute()
}

// violations:2
// Invalid: Multiple direct Execute() calls
func (r *ExecuteWithRetryTestResource) InvalidMultipleDirectExecute(ctx context.Context) {
	request1 := ApiGetHypervisorRequest{}
	_, _, _ = request1.Execute()

	request2 := ApiGetHypervisorRequest{}
	_, _, _ = request2.Execute()
}

// violations:1
// Invalid: GET operation with AddRequestData should use ExecuteWithRetry
func (r *ExecuteWithRetryTestResource) InvalidGetWithAddRequestData(ctx context.Context, client *MockClient) {
	getRequest := ApiGetHypervisorRequest{}
	_, _, _ = citrixdaasclient.AddRequestData(getRequest, client).Execute()
}

// violations:1
// Invalid: Fetch operation with AddRequestData should use ExecuteWithRetry
func (r *ExecuteWithRetryTestResource) InvalidFetchWithAddRequestData(ctx context.Context, client *MockClient) {
	fetchRequest := ApiFetchAdministratorsRequest{}
	_, _, _ = citrixdaasclient.AddRequestData(fetchRequest, client).Execute()
}

// violations:1
// Invalid: Fetch operation with AddRequestData().Async() should use ExecuteWithRetry
func (r *ExecuteWithRetryTestResource) InvalidAsyncFetchWithAddRequestData(ctx context.Context, client *MockClient) {
	fetchRequest := ApiFetchAdministratorsRequest{}
	_, _, _ = citrixdaasclient.AddRequestData(fetchRequest, client).Async(true).Execute()
}

// violations:1
// Invalid: GET operation with service name in type (ApiTagsGetTagRequest)
func (r *ExecuteWithRetryTestResource) InvalidTagsGetWithAddRequestData(ctx context.Context, client *MockClient) {
	getRequest := ApiTagsGetTagRequest{}
	_, _, _ = citrixdaasclient.AddRequestData(getRequest, client).Execute()
}

// violations:1
// Invalid: GET operation with service name - direct Execute()
func (r *ExecuteWithRetryTestResource) InvalidDeliveryGroupGetDirectExecute(ctx context.Context, client *MockClient) {
	getRequest := ApiDeliveryGroupsGetDeliveryGroupRequest{}
	_, _, _ = getRequest.Execute()
}

// violations:1
// Invalid: GET operation with service name and chained Async()
func (r *ExecuteWithRetryTestResource) InvalidHypervisorsGetWithAsyncChain(ctx context.Context, client *MockClient) {
	getRequest := ApiHypervisorsGetHypervisorsAndResourcePoolsRequest{}
	_, _, _ = citrixdaasclient.AddRequestData(getRequest, client).Async(false).Execute()
}

// violations:1
// Invalid: List operation with service name in type
func (r *ExecuteWithRetryTestResource) InvalidMachineCatalogsListDirectExecute(ctx context.Context, client *MockClient) {
	listRequest := ApiMachineCatalogsListMachineCatalogsRequest{}
	_, _, _ = listRequest.Execute()
}

// StoreFront test cases
// NOTE: StoreFront operations should NOT use ExecuteWithRetry because their Execute() methods
// return (result, error) instead of (result, *http.Response, error)

// Valid: StoreFront GET operations use direct Execute()
func (r *ExecuteWithRetryTestResource) ValidStoreFrontGetDirectExecute(ctx context.Context, client *MockClient) {
	getRequest := STFDeploymentGetSTFDeploymentRequest{}
	_, _, _ = getRequest.Execute()
}

// Valid: Using direct Execute() for StoreFront non-GET operations (Create, Set, Clear)
func (r *ExecuteWithRetryTestResource) ValidStoreFrontCreateDirectExecute(ctx context.Context, client *MockClient) {
	createRequest := STFDeploymentCreateSTFDeploymentRequest{}
	_, _, _ = createRequest.Execute()
}

func (r *ExecuteWithRetryTestResource) ValidStoreFrontSetDirectExecute(ctx context.Context, client *MockClient) {
	setRequest := STFDeploymentSetSTFDeploymentRequest{}
	_, _ = setRequest.Execute()
}

func (r *ExecuteWithRetryTestResource) ValidStoreFrontClearDirectExecute(ctx context.Context, client *MockClient) {
	clearRequest := STFDeploymentClearSTFDeploymentRequest{}
	_, _ = clearRequest.Execute()
}

// Valid: StoreFront operations are excluded - can use ExecuteWithRetry (though not recommended)
// The linter only enforces ExecuteWithRetry for non-StoreFront GET operations
func (r *ExecuteWithRetryTestResource) ValidStoreFrontGetWithExecuteWithRetry(ctx context.Context, client *MockClient) {
	getRequest := STFDeploymentGetSTFDeploymentRequest{}
	_, _, _ = citrixdaasclient.ExecuteWithRetry(getRequest, client)
}

// Valid: StoreFront operations are excluded - can use ExecuteWithRetry (though not recommended)
func (r *ExecuteWithRetryTestResource) ValidStoreFrontCreateWithExecuteWithRetry(ctx context.Context, client *MockClient) {
	createRequest := STFDeploymentCreateSTFDeploymentRequest{}
	_, _, _ = citrixdaasclient.ExecuteWithRetry(createRequest, client)
}
