# This is a Go Test workflow that is manually triggered

name: Provider Go Test workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI
        description: 'Release version that is tested against.'
        # Default value if no value is explicitly provided
        default: 'Latest'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "gotest"
  gotest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v4
      
      - name: Login via Az module
        uses: azure/login@v2
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
          enable-AzPSSession: true 
      
      - name: Run Azure PowerShell inline script
        uses: azure/powershell@v2
        with:
          inlineScript: |
            ./scripts/test-env-power-management.ps1 `
              -ClientId ${{secrets.ClientId}} `
              -ClientSecret ${{secrets.ClientSecret}} `
              -DomainFqdn ${{env.DomainFqdn}} `
              -Hostname ${{env.Hostname}} `
              -AzureClientId ${{secrets.AzureClientId}} `
              -AzureClientSecret ${{secrets.AzureClientSecret}} `
              -AzureTenantId ${{secrets.AzureTenantId}} `
              -AzureSubscriptionId ${{env.AzureSubscriptionId}} `
              -AzureResourceGroupName ${{env.AzureResourceGroupName}} `
              -AzureDdcVmName ${{env.AzureDdcVmName}} `
              -AzureAdVmName ${{env.AzureAdVmName}} `
              -DisableSSLValidation $true
          azPSVersion: "latest"
