# This is a Go Test workflow that is manually triggered

name: GoTest

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI
        description: 'Release version that is tested against.'
        # Default value if no value is explicitly provided
        default: 'Latest'
        # Input has to be provided for the workflow to run
        required: false
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "gotest"
  gotest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v4
        with: 
          ref: test-github-action
          # token: ${{secrets.CHECKOUT_TOKEN}}

      # - name: Install Az PowerShell
      #   shell: pwsh
      #   run: |
      #     Install-Module -Name Az.Compute -Repository PSGallery -Force -ErrorAction Stop
      
      - name: Run Azure PowerShell inline script
        uses: azure/powershell@v2
        with:
          inlineScript: |
            ./scripts/test-env-power-management/azure_env.ps1 `
              -ClientId ${{secrets.CLIENT_ID}} `
              -ClientSecret ${{secrets.CLIENT_SECRET}} `
              -DomainFqdn ${{secrets.DOMAIN_FQDN}} `
              -Hostname ${{secrets.HOSTNAME}} `
              -AzureClientId ${{secrets.AZURE_CLIENT_ID}} `
              -AzureClientSecret ${{secrets.AZURE_CLIENT_SECRET}} `
              -AzureTenantId ${{secrets.AZURE_TENANT_ID}} `
              -AzureSubscriptionId ${{secrets.AZURE_SUBSCRIPTION_ID}} `
              -AzureResourceGroupName ${{vars.AZURE_RESOURCE_GROUP_NAME}} `
              -AzureDdcVmName ${{vars.AZURE_DDC_VM_NAME}} `
              -AzureAdVmName ${{vars.AZURE_AD_VM_NAME}} `
              -DisableSSLValidation $true
          azPSVersion: "latest"